### ISSUE TITLE
Cleanup and introduce new standards after 0.4.0 release for version 0.5.0

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#294]
I have noticed that as the code has grown over time, that the code could use some cleanup and it becomes more useful to have stricter standards to prevent the need for future cleanups. I think it is best to do that right after the release so it sets the standard for the 0.5.0 release early. This is tracking some of the efforts to do that.

- [X] Use selected clang-tidy check to modernize and clean the code. Also add the option in cmake to do this automatically, but do not turn this on by default. (#293)
- [X] Clean up header files with IWYU and custom script. This is has been a bit messy and a lot of checking by hand, but the result is an improvment. So I am not going to include the codes I used to do this for now. (#295 )
- [X] More cleanup needed for the headers with clang-tidy (#296)
- [X] ~~Use clang format on code once (but do not make it automatic yet). Astyle will still have the final say to keep compatibility with aspect, but clang-format can enforce some thing astyle can't. Related to #176.~~ Not going to enforce this for this release.
- [X] ~~Decide on use of tailing return type and auto use. Although I am generally favorable to the idea of changing to the tailing return type format, it is a bit change and I am not sure whether I want to do this yet for version 0.5.0.~~ I don't think it should be changed to that format for release 0.5.0. It is too big of a change and it would break style with aspect without any major advantages. Will reconsider if good arguments are raised.
