### ISSUE TITLE
Todo: release 0.5.0

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#493]
- [X] run spell checker #494  and #495 
- [X] run clang-analyzer scan-build (https://clang-analyzer.llvm.org/command-line.html): No bugs found.
- [x] run clang tidy: #497
- [x] wait for reviews from ASPECT (https://github.com/geodynamics/aspect/pull/5164)
- [x] make new zenodo doi (before the release) to include in the new release. (#499)
- [x] increase version number (#499)
- [ ] make release
