### ISSUE TITLE
[Tracking issue] Improve API and Developer documentation

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#532]
The developer documentation is currently still mostly missing. This issue keeps track of the API and Developer manual which still need to be written. Please comment below if you are working on one of these pages, so no double work is done. Also don't forget to mention this issue in your pull request, so that it can be ticket off when it is merged.

**API manual**
- [ ] API design
- [ ] Available APIs
- [ ] API in different languages (FFI)

**Developer Manual**
- [ ] How to start developing and contributing
    - [ ] required and recommended tools
        - [ ] Git
        - [ ] Astyle
        - [ ] IDE
    - [ ] Contributing to the GWB
        - [ ] Helping others
        - [ ] Making a pull request
        - [ ] Pull request review process
            - [ ] What is continuous integration?
            - [ ] Testers
            - [ ] Code coverage
            - [ ] Benchmarking
            - [ ] Documentation testing
        - [ ] Pull request merging
- [ ] Contributing to the documentation
    - [ ] Important syntax
    - [ ] Documentation style guide
    - [ ] Documentation testing
    - [ ] Tips and tricks
    - [ ] The review process
- [ ] Contributing to the code
    - [ ] Code documentation and Doxygen 
    - [ ] Code conventions
    - [ ] Code Style Guide
    - [ ] Testing your code
        - [ ] Unit tests
        - [ ] integration testers
            - [ ] App tester
            - [ ] Visualization tester
            - [ ] Wrapper tester
    - [ ] Tips and tricks
    - [ ] Review process
- [ ] Developing for the GWB
    - [ ] Code structure
    - [ ] Creating new plugins
    - [ ] Changing or adding code
    - [ ] Creating a new plugin system
    - [ ] Creating new tools

**Comment by alarshi** [comment]
I am working on `Creating new plugins`
