### ISSUE TITLE
Release 0.6

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#670]
Due to wanting to submit the JOSS paper for the world builder, I would like to release version 0.6 ~~either over the weekend or early next week~~ probably end of the week, but could be later. This allow the version number to be upgraded to 1.0-pre. The 1.0 release would then coincide with the the publication of the paper.  

Here is the todo list:
- [x] run spell checker (#678)
- [x] run clang-analyzer scan-build (https://clang-analyzer.llvm.org/command-line.html) -- No bugs found.
- [x] run clang tidy (#679)
- [x] check and fix changelog entries (#681)
- [x] Update copyright year sphinx, include and header files (#684)
- [x] confirm status of cmake issues with aspect integration (#686 and https://github.com/geodynamics/aspect/pull/5592)
- [x] Confirm aspect pull request review (https://github.com/geodynamics/aspect/pull/5584)
- [x] make new zenodo doi (before the release) to include in the new release -- Done: 10.5281/zenodo.10794862
- [x] increase version number (#695)
- [x] make release
- [x] post-release version bump (#698) --> Note: Benchmarks won't work until this pull request is merged.

Please let me know if there are any other items which should be checked before the release, or which may delay it.

**Comment by MFraters** [comment]
GWB v0.6.0 release complete! :tada:
